### ISSUE TITLE
Update INSTALL text

### ISSUE THREAD

**Issue by npmaling** [lifelines/lifelines#336]
Is the INSTALL text up-to-date regarding the build process? I notice in the cloning process and the download zip file do not contain a configure script.

**Comment by memmerto** [comment]
The text in INSTALL is correct for those using a release package.  Parts of the INSTALL file are out of date.

If you're cloning master, you will need to run build/autogen.sh (and have all of the GNU auto tools installed) so that it can build the configure script and all the makefiles.  Then you can proceed with the normal process. (This is documented in docs/dev/README.DEVELOPERS, which also is slightly out of date.)
