### ISSUE TITLE
Parser Error for random out of place number

### ISSUE THREAD

**Issue by stevedum** [lifelines/lifelines#351]
The following script
proc main()
{
    "hi there folks" nl()
    8
    "by for now" nl()
}
Produces the following 'Error' when compiling the script
itype(node) is 1
HUH, HUH, HUH, HUNH!
Program was not run because of errors.

Shouldn't it be something more like

Aborting: Syntax Error (syntax error): ./a.ll: line 4, char 3
Program contains errors.

**Comment by memmerto** [comment]
This problem also occurs when a floating-point constant is used (eg, 8.00).

String constants are implicitly allowed since this is how strings are "printed".

The LL report language expects that integer and floating-point values are converted to strings via d() and f(), respectively, in order to print them.

Did we want to retain this explicit conversion, or did we want to apply it implicitly?

**Comment by memmerto** [comment]
Scratch the idea of implicit conversion.  It requires a lot more code to be written than anticipated.

Handle unexpected integer and floating-point constants with a helpful error messaging suggesting the use of d() and f(), respectively.
