### ISSUE TITLE
Failure of 'Q' menu option to offer change of database - Mac OS and Ubuntu

### ISSUE THREAD

**Issue by MichaelHendry** [lifelines/lifelines#397]
This arises from line 79 of selectdb.c:

if (!*dbrequested) {

Replacing this with:

if (!*dbrequested[0]) {

sorts the problem.

**Comment by memmerto** [comment]
Ugh.  Yes, I can see how this would help.  The code is very inconsistent in how it treats an "empty string" -- sometimes it's NULL pointer, sometimes it's a one-byte allocation set to '\0'.  I will look through this in more detail.  I remember doing some work in this area to avoid memory leaks and likely changed the semantics of something in the process.

**Comment by MichaelHendry** [comment]
This is one of those pointer-to-a-pointer-to-a-pointer problems which does my head in!

This also works...

	if (!**dbrequested) {

...and is probably the tidiest way of achieving the desired result.

**Comment by memmerto** [comment]
> This is one of those pointer-to-a-pointer-to-a-pointer problems which does my head in!
> 
> This also works...
> 
> ```
> if (!**dbrequested) {
> ```
> 
> ...and is probably the tidiest way of achieving the desired result.

Except that it is misleading.  Because of the aforementioned concerns with what an "empty string" is, we may need two checks here.
1) a check that the pointer to a pointer is not NULL, which is what the current code does.  It would be better written as ```*dbrequested != NULL```.   (Note that tThe ASSERT(dbrequested) validates that the first pointer is valid.)
2) a check that the pointer to a pointer does not point to a string with a single NULL character.  What you suggest would do this, but it's better written as (*dbrequested)[0] != '\0'

**Comment by memmerto** [comment]
From main.c (and llexec.c), you can see how we pass in either a non-empty or an empty string:

```
    377                 if (!alldone && c>0) {
    378                         dbrequested = strsave(argv[optind]);
    379                 } else {
    380                         strupdate(&dbrequested, "");
    381                 }
    382                 if (!select_database(&dbrequested, alteration, &errmsg)) {
```

In both cases we pass in a valid STRING of some sort, so we can:
1) assume (but validate) that the double-pointer is valid
2) check that the string is not "empty", using the revised check you suggested.
