### ISSUE TITLE
Portability bug in load_nkey_list() / save_nkey_list()

### ISSUE THREAD

**Issue by memmerto** [lifelines/lifelines#405]
These functions are written with different styles, and won't work properly when INT is a 64-bit integer.

**Comment by MichaelHendry** [comment]
load_nkey_list() DOES work properly when INT is a 64-bit integer, but wouldn't work if it were 32-bit.
From inspection, I think save_nkey_list() would work correctly in either circumstance, because the sizes of next, count and temp aren't important as long as temp is big enough to hold the largest address needed by a pointer.

Which raises the questions:
1. Is the address bus guaranteed to be no wider than the data bus?
2. Am I overthinking this before I've had my morning dose of caffeine?

**Comment by memmerto** [comment]
1) It depends on the architecture.
2) Possibly :)

Carefully look at the fwrite() calls in save_nkey_list().  How is the data written here read by load_nkey_list()?

**Comment by memmerto** [comment]
The problem is with `histp->listp[].keynum` which is defined as INT but is read/written as INT32.

This value could be truncated during `save_nkey_list()`.  This is a pre-existing legacy problem.

LifeLines defines a maximum key width of 8 bytes, of which the first byte is a character identifier, leaving 7 bytes for the integer component.  9,999,999 is the maximum key value (MAXKEYNUMBER).

Since this is greater than the maximum signed integer range of 2,147,483,648, truncation could occur when values are written out.

These routines are only used to save/load the view and change history lists, which is a pure UI construct, and not part of the core database.  I'm not sure who has more than 2 billion records in their database, and would have entries like this in their view/change history.  In any case, avoid this problem by not writing out entries that would be truncated.

(Fixing this *properly* would require database changes and migration which I don't think is warranted here.)

**Comment by memmerto** [comment]
Looks like I was off by a factor of 1000.

Since this (9,999,999) is **not** greater than the maximum signed integer range of 2,147,483,648, truncation **would not** occur when values are written out.
