### ISSUE TITLE
macos make fails yacc.c

### ISSUE THREAD

**Issue by veronicellidae-outblacken** [lifelines/lifelines#438]
test -f yacc.c || /bin/sh ../../build/autotools/ylwrap yacc.y y.tab.c yacc.c y.tab.h `echo yacc.c | sed -e s/cc$/hh/ -e s/cpp$/hpp/ -e s/cxx$/hxx/ -e s/c++$/h++/ -e s/c$/h/` y.output yacc.output -- bison -y -d -t 
/Users/veron/code/lifelines/src/interp/yacc.y:78.9-22: syntax error, unexpected identifier, expecting string
make[3]: *** [yacc.c] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

Line 78 in yacc.y is 

%define api.value.type {PNODE}

**Comment by memmerto** [comment]
What OS/version/distro?
What version of bison are you using?

**Comment by veronicellidae-outblacken** [comment]
Mac OS X 10.15.7 19H1419
bison (GNU Bison) 2.3
LifeLines Source Release, Version 3.2.0

**Comment by MichaelHendry** [comment]
On 21 Nov 2021, at 20:10, veronicellidae-outblacken ***@***.***> wrote:

> 
> 
> Mac OS X 10.15.7 19H1419
> bison (GNU Bison) 2.3
> LifeLines Source Release, Version 3.2.0


I had a problem like this in 2018, resolved by installing bison 3.1 on my iMac.

Here’s a note on what I did from LINES-L

brew install bison
echo 'export PATH=3D"/usr/local/opt/bison/bin:$PATH"' >> ~/.bash_profile
export LDFLAGS=3D"-L/usr/local/opt/bison/lib"

This forced the use of the new version of bison in place of /usr/bin/biso=
n and allowed "./configure", "make", and "make install" to function to co=
mpletion.

Michael

**Comment by veronicellidae-outblacken** [comment]
I tried that. Unfortunately I get the same error. How would I check that the `configure` and `make` are using the correct `bison` now?

**Comment by MichaelHendry** [comment]
On 23 Nov 2021, at 18:45, veronicellidae-outblacken ***@***.***> wrote:

> 
> 
> I tried that. Unfortunately I get the same error. How would I check that the configure and make are using the correct bison now?


try:

bison —version

Michael

**Comment by veronicellidae-outblacken** [comment]
bison --version
bison (GNU Bison) 2.3

**Comment by MichaelHendry** [comment]
On 23 Nov 2021, at 20:17, veronicellidae-outblacken ***@***.***> wrote:
> 
> 
> bison --version
> bison (GNU Bison) 2.3
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> 

Really sorry to have wasted your time with a mangled version of my posting - LINES-L does weird stuff with messages!

Here’s a copy-and-paste of my original posting, which you will see doesn’t have the intrusive “3D” in two of the lines I’d sent to you.

I think that if you use the 2nd and 3rd lines without the “3D” you should be OK. Check with “bison —version” to be sure.

It’s possible you may have to log out and log in again to get this to work, because ~/.bash_profile may not be read until you log in again.

Michael



Mime-Version:	
1.0
Content-Type:	
text/plain; charset="UTF-8"
Date:	
Sat, 20 Oct 2018 02:29:46 -0500
Reply-To:	
LifeLines Genealogical System ***@***.***>
Subject:	
Re: Lifelines shuts down with "abort trap 6" message
Content-Transfer-Encoding:	
quoted-printable
Message-ID:	
***@***.***>
Sender:	
LifeLines Genealogical System ***@***.***>
From:	
Michael Hendry ***@***.***>
Parts/Attachments:	
text/plain (12 lines)
Success!

I eventually found this advice on stackoverflow:

brew install bison
echo 'export PATH="/usr/local/opt/bison/bin:$PATH"' >> ~/.bash_profile
export LDFLAGS="-L/usr/local/opt/bison/lib"

This forced the use of the new version of bison in place of /usr/bin/bison and allowed "./configure", "make", and "make install" to function to completion.

Michael

**Comment by memmerto** [comment]
My notes are unfortunately poor, but src/interp/yacc.y has comments indicating support for bison 2.7 and 3.1.
The bison 2.3 that ships with macOS 10.15 Catalina is too old.

Installing a newer version of bison, and ensuring that it is found before the system bison, meets this minimum requirement.

I've updated INSTALL with the minimum version of bison required, as well as the process to install a newer one if required.
